name: Jest tests

on: push

jobs:
    tests:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
    
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 14.x
          
          - name: Run tests
            run: |
              npm ci
              npm test